### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Felli** [GreenMeteor/humhub-patreon-module#1]
The following is needed to be finished before it's ready to be submitted to the marketplace.
- [x] URL to widget
- [x] Rework the temp fix to a complete
- [ ] Load goal percentage (On-hold)
- [ ] Complete goal code (On-hold)
- [ ] Translations (#2)
- [ ] Patreon Widget Breaks Stream Loading (#7)
